FROM node:20.0.0 AS builder
WORKDIR /k6
COPY . .
RUN --mount=type=cache,target=/usr/local/share/.cache/yarn/v6 \ 
yarn install --frozen-lockfile && yarn build

FROM grafana/k6:0.44.1 AS runner
WORKDIR /k6
COPY --from=builder /k6/dist ./dist
